//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.transmittal_ws {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="transmittal_ws.serviceSoap")]
    public interface serviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PODetails(string pono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PODetailsAsync(string pono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable POItems(int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> POItemsAsync(int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPAmount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double PPMPAmount(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PPMPAmountAsync(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PPMPItems(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PPMPItemsAsync(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPLumpsum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PPMPLumpsum(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPLumpsum", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PPMPLumpsumAsync(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPNonOffice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PPMPNonOffice(int year, int officeid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPNonOffice", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PPMPNonOfficeAsync(int year, int officeid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTransactions(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTransactionsAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetItems(string transno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetItemsAsync(string transno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllPPMPItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllPPMPItems(int officeid, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllPPMPItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllPPMPItemsAsync(int officeid, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetKey(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKey", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetKeyAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Items", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Items();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Items", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveBarcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SaveBarcode(int itemid, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveBarcode", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SaveBarcodeAsync(int itemid, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetItem(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetItemAsync(string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPRStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPRStatus(int prid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPRStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPRStatusAsync(int prid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPR(int officeid, int cyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPR", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPRAsync(int officeid, int cyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PRStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PRStatus(int prid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PRStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PRStatusAsync(int prid);
        
        // CODEGEN: Parameter 'bytes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IMS.transmittal_ws.GetUpdatesResponse GetUpdates(IMS.transmittal_ws.GetUpdatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdates", ReplyAction="*")]
        System.Threading.Tasks.Task<IMS.transmittal_ws.GetUpdatesResponse> GetUpdatesAsync(IMS.transmittal_ws.GetUpdatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SaveDocument(int officeid, string subject, int eid, string uniquerefno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDocument", ReplyAction="*")]
        System.Threading.Tasks.Task SaveDocumentAsync(int officeid, string subject, int eid, string uniquerefno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPRStatusdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPRStatusdate(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPRStatusdate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPRStatusdateAsync(int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPUtilization", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PPMPUtilization(int cyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPUtilization", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PPMPUtilizationAsync(int cyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransmittalAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TransmittalAction(int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransmittalAction", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TransmittalActionAsync(int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewTransmittal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable NewTransmittal(int trailid, int officeid, int eid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewTransmittal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> NewTransmittalAsync(int trailid, int officeid, int eid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTransmittalTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AddTransmittalTransaction(int transid, string uniquerefno, int poid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTransmittalTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AddTransmittalTransactionAsync(int transid, string uniquerefno, int poid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTransmittalTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteTransmittalTransaction(int transdetailsid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTransmittalTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteTransmittalTransactionAsync(int transdetailsid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTransmittal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendTransmittal(int transid, int eid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTransmittal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendTransmittalAsync(int transid, int eid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewTransmittal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ViewTransmittal(string transactionno, int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewTransmittal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ViewTransmittalAsync(string transactionno, int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewTransmittalTransactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ViewTransmittalTransactions(string transid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewTransmittalTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ViewTransmittalTransactionsAsync(string transid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveTransmittal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReceiveTransmittal(int transid, string eid, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveTransmittal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReceiveTransmittalAsync(int transid, string eid, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewTransmittalInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ViewTransmittalInfo(string transactionno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewTransmittalInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ViewTransmittalInfoAsync(string transactionno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceivedTransmittal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReceivedTransmittal(int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceivedTransmittal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReceivedTransmittalAsync(int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTransactionRemarks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateTransactionRemarks(int transdetailsid, string remarks, int eid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTransactionRemarks", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateTransactionRemarksAsync(int transdetailsid, string remarks, int eid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckSent(string transactionno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSent", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckSentAsync(string transactionno);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdates", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUpdatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bytes;
        
        public GetUpdatesRequest() {
        }
        
        public GetUpdatesRequest(string fileName, string contentType, byte[] bytes) {
            this.fileName = fileName;
            this.contentType = contentType;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdatesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUpdatesResponse {
        
        public GetUpdatesResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceSoapChannel : IMS.transmittal_ws.serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceSoapClient : System.ServiceModel.ClientBase<IMS.transmittal_ws.serviceSoap>, IMS.transmittal_ws.serviceSoap {
        
        public serviceSoapClient() {
        }
        
        public serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable PODetails(string pono) {
            return base.Channel.PODetails(pono);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PODetailsAsync(string pono) {
            return base.Channel.PODetailsAsync(pono);
        }
        
        public System.Data.DataTable POItems(int officeid) {
            return base.Channel.POItems(officeid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> POItemsAsync(int officeid) {
            return base.Channel.POItemsAsync(officeid);
        }
        
        public double PPMPAmount(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPAmount(year, officeid, programid, accountid);
        }
        
        public System.Threading.Tasks.Task<double> PPMPAmountAsync(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPAmountAsync(year, officeid, programid, accountid);
        }
        
        public System.Data.DataTable PPMPItems(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPItems(year, officeid, programid, accountid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PPMPItemsAsync(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPItemsAsync(year, officeid, programid, accountid);
        }
        
        public System.Data.DataTable PPMPLumpsum(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPLumpsum(year, officeid, programid, accountid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PPMPLumpsumAsync(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPLumpsumAsync(year, officeid, programid, accountid);
        }
        
        public System.Data.DataTable PPMPNonOffice(int year, int officeid, int accountid) {
            return base.Channel.PPMPNonOffice(year, officeid, accountid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PPMPNonOfficeAsync(int year, int officeid, int accountid) {
            return base.Channel.PPMPNonOfficeAsync(year, officeid, accountid);
        }
        
        public System.Data.DataTable GetTransactions(int year) {
            return base.Channel.GetTransactions(year);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTransactionsAsync(int year) {
            return base.Channel.GetTransactionsAsync(year);
        }
        
        public System.Data.DataTable GetItems(string transno) {
            return base.Channel.GetItems(transno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetItemsAsync(string transno) {
            return base.Channel.GetItemsAsync(transno);
        }
        
        public System.Data.DataTable AllPPMPItems(int officeid, int year) {
            return base.Channel.AllPPMPItems(officeid, year);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllPPMPItemsAsync(int officeid, int year) {
            return base.Channel.AllPPMPItemsAsync(officeid, year);
        }
        
        public string GetKey(string id) {
            return base.Channel.GetKey(id);
        }
        
        public System.Threading.Tasks.Task<string> GetKeyAsync(string id) {
            return base.Channel.GetKeyAsync(id);
        }
        
        public System.Data.DataTable Items() {
            return base.Channel.Items();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ItemsAsync() {
            return base.Channel.ItemsAsync();
        }
        
        public System.Data.DataTable AllItems() {
            return base.Channel.AllItems();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllItemsAsync() {
            return base.Channel.AllItemsAsync();
        }
        
        public int SaveBarcode(int itemid, string code) {
            return base.Channel.SaveBarcode(itemid, code);
        }
        
        public System.Threading.Tasks.Task<int> SaveBarcodeAsync(int itemid, string code) {
            return base.Channel.SaveBarcodeAsync(itemid, code);
        }
        
        public System.Data.DataTable GetItem(string barcode) {
            return base.Channel.GetItem(barcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetItemAsync(string barcode) {
            return base.Channel.GetItemAsync(barcode);
        }
        
        public System.Data.DataTable GetPRStatus(int prid) {
            return base.Channel.GetPRStatus(prid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPRStatusAsync(int prid) {
            return base.Channel.GetPRStatusAsync(prid);
        }
        
        public System.Data.DataTable GetPR(int officeid, int cyear) {
            return base.Channel.GetPR(officeid, cyear);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPRAsync(int officeid, int cyear) {
            return base.Channel.GetPRAsync(officeid, cyear);
        }
        
        public string PRStatus(int prid) {
            return base.Channel.PRStatus(prid);
        }
        
        public System.Threading.Tasks.Task<string> PRStatusAsync(int prid) {
            return base.Channel.PRStatusAsync(prid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMS.transmittal_ws.GetUpdatesResponse IMS.transmittal_ws.serviceSoap.GetUpdates(IMS.transmittal_ws.GetUpdatesRequest request) {
            return base.Channel.GetUpdates(request);
        }
        
        public void GetUpdates(string fileName, string contentType, byte[] bytes) {
            IMS.transmittal_ws.GetUpdatesRequest inValue = new IMS.transmittal_ws.GetUpdatesRequest();
            inValue.fileName = fileName;
            inValue.contentType = contentType;
            inValue.bytes = bytes;
            IMS.transmittal_ws.GetUpdatesResponse retVal = ((IMS.transmittal_ws.serviceSoap)(this)).GetUpdates(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMS.transmittal_ws.GetUpdatesResponse> IMS.transmittal_ws.serviceSoap.GetUpdatesAsync(IMS.transmittal_ws.GetUpdatesRequest request) {
            return base.Channel.GetUpdatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMS.transmittal_ws.GetUpdatesResponse> GetUpdatesAsync(string fileName, string contentType, byte[] bytes) {
            IMS.transmittal_ws.GetUpdatesRequest inValue = new IMS.transmittal_ws.GetUpdatesRequest();
            inValue.fileName = fileName;
            inValue.contentType = contentType;
            inValue.bytes = bytes;
            return ((IMS.transmittal_ws.serviceSoap)(this)).GetUpdatesAsync(inValue);
        }
        
        public void SaveDocument(int officeid, string subject, int eid, string uniquerefno) {
            base.Channel.SaveDocument(officeid, subject, eid, uniquerefno);
        }
        
        public System.Threading.Tasks.Task SaveDocumentAsync(int officeid, string subject, int eid, string uniquerefno) {
            return base.Channel.SaveDocumentAsync(officeid, subject, eid, uniquerefno);
        }
        
        public System.Data.DataTable GetPRStatusdate(int year) {
            return base.Channel.GetPRStatusdate(year);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPRStatusdateAsync(int year) {
            return base.Channel.GetPRStatusdateAsync(year);
        }
        
        public System.Data.DataTable PPMPUtilization(int cyear) {
            return base.Channel.PPMPUtilization(cyear);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PPMPUtilizationAsync(int cyear) {
            return base.Channel.PPMPUtilizationAsync(cyear);
        }
        
        public System.Data.DataTable TransmittalAction(int officeid) {
            return base.Channel.TransmittalAction(officeid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TransmittalActionAsync(int officeid) {
            return base.Channel.TransmittalActionAsync(officeid);
        }
        
        public System.Data.DataTable NewTransmittal(int trailid, int officeid, int eid) {
            return base.Channel.NewTransmittal(trailid, officeid, eid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> NewTransmittalAsync(int trailid, int officeid, int eid) {
            return base.Channel.NewTransmittalAsync(trailid, officeid, eid);
        }
        
        public System.Data.DataTable AddTransmittalTransaction(int transid, string uniquerefno, int poid) {
            return base.Channel.AddTransmittalTransaction(transid, uniquerefno, poid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AddTransmittalTransactionAsync(int transid, string uniquerefno, int poid) {
            return base.Channel.AddTransmittalTransactionAsync(transid, uniquerefno, poid);
        }
        
        public string DeleteTransmittalTransaction(int transdetailsid) {
            return base.Channel.DeleteTransmittalTransaction(transdetailsid);
        }
        
        public System.Threading.Tasks.Task<string> DeleteTransmittalTransactionAsync(int transdetailsid) {
            return base.Channel.DeleteTransmittalTransactionAsync(transdetailsid);
        }
        
        public string SendTransmittal(int transid, int eid) {
            return base.Channel.SendTransmittal(transid, eid);
        }
        
        public System.Threading.Tasks.Task<string> SendTransmittalAsync(int transid, int eid) {
            return base.Channel.SendTransmittalAsync(transid, eid);
        }
        
        public System.Data.DataTable ViewTransmittal(string transactionno, int officeid) {
            return base.Channel.ViewTransmittal(transactionno, officeid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ViewTransmittalAsync(string transactionno, int officeid) {
            return base.Channel.ViewTransmittalAsync(transactionno, officeid);
        }
        
        public System.Data.DataTable ViewTransmittalTransactions(string transid) {
            return base.Channel.ViewTransmittalTransactions(transid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ViewTransmittalTransactionsAsync(string transid) {
            return base.Channel.ViewTransmittalTransactionsAsync(transid);
        }
        
        public string ReceiveTransmittal(int transid, string eid, string data) {
            return base.Channel.ReceiveTransmittal(transid, eid, data);
        }
        
        public System.Threading.Tasks.Task<string> ReceiveTransmittalAsync(int transid, string eid, string data) {
            return base.Channel.ReceiveTransmittalAsync(transid, eid, data);
        }
        
        public System.Data.DataSet ViewTransmittalInfo(string transactionno) {
            return base.Channel.ViewTransmittalInfo(transactionno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ViewTransmittalInfoAsync(string transactionno) {
            return base.Channel.ViewTransmittalInfoAsync(transactionno);
        }
        
        public System.Data.DataTable ReceivedTransmittal(int officeid) {
            return base.Channel.ReceivedTransmittal(officeid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReceivedTransmittalAsync(int officeid) {
            return base.Channel.ReceivedTransmittalAsync(officeid);
        }
        
        public string UpdateTransactionRemarks(int transdetailsid, string remarks, int eid) {
            return base.Channel.UpdateTransactionRemarks(transdetailsid, remarks, eid);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTransactionRemarksAsync(int transdetailsid, string remarks, int eid) {
            return base.Channel.UpdateTransactionRemarksAsync(transdetailsid, remarks, eid);
        }
        
        public string CheckSent(string transactionno) {
            return base.Channel.CheckSent(transactionno);
        }
        
        public System.Threading.Tasks.Task<string> CheckSentAsync(string transactionno) {
            return base.Channel.CheckSentAsync(transactionno);
        }
    }
}
