//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IMS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pmisEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pmisEntities object using the connection string found in the 'pmisEntities' section of the application configuration file.
        /// </summary>
        public pmisEntities() : base("name=pmisEntities", "pmisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pmisEntities object.
        /// </summary>
        public pmisEntities(string connectionString) : base(connectionString, "pmisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pmisEntities object.
        /// </summary>
        public pmisEntities(EntityConnection connection) : base(connection, "pmisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OfficeDescription> OfficeDescriptions
        {
            get
            {
                if ((_OfficeDescriptions == null))
                {
                    _OfficeDescriptions = base.CreateObjectSet<OfficeDescription>("OfficeDescriptions");
                }
                return _OfficeDescriptions;
            }
        }
        private ObjectSet<OfficeDescription> _OfficeDescriptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwLoginParameter> vwLoginParameters
        {
            get
            {
                if ((_vwLoginParameters == null))
                {
                    _vwLoginParameters = base.CreateObjectSet<vwLoginParameter>("vwLoginParameters");
                }
                return _vwLoginParameters;
            }
        }
        private ObjectSet<vwLoginParameter> _vwLoginParameters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwMergeAllEmployee> vwMergeAllEmployees
        {
            get
            {
                if ((_vwMergeAllEmployees == null))
                {
                    _vwMergeAllEmployees = base.CreateObjectSet<vwMergeAllEmployee>("vwMergeAllEmployees");
                }
                return _vwMergeAllEmployees;
            }
        }
        private ObjectSet<vwMergeAllEmployee> _vwMergeAllEmployees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OfficeDescriptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOfficeDescriptions(OfficeDescription officeDescription)
        {
            base.AddObject("OfficeDescriptions", officeDescription);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwLoginParameters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwLoginParameters(vwLoginParameter vwLoginParameter)
        {
            base.AddObject("vwLoginParameters", vwLoginParameter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwMergeAllEmployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwMergeAllEmployees(vwMergeAllEmployee vwMergeAllEmployee)
        {
            base.AddObject("vwMergeAllEmployees", vwMergeAllEmployee);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pmisModel", Name="OfficeDescription")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OfficeDescription : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OfficeDescription object.
        /// </summary>
        /// <param name="officeID">Initial value of the OfficeID property.</param>
        public static OfficeDescription CreateOfficeDescription(global::System.Int32 officeID)
        {
            OfficeDescription officeDescription = new OfficeDescription();
            officeDescription.OfficeID = officeID;
            return officeDescription;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OfficeID
        {
            get
            {
                return _OfficeID;
            }
            set
            {
                if (_OfficeID != value)
                {
                    OnOfficeIDChanging(value);
                    ReportPropertyChanging("OfficeID");
                    _OfficeID = StructuralObject.SetValidValue(value, "OfficeID");
                    ReportPropertyChanged("OfficeID");
                    OnOfficeIDChanged();
                }
            }
        }
        private global::System.Int32 _OfficeID;
        partial void OnOfficeIDChanging(global::System.Int32 value);
        partial void OnOfficeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeName
        {
            get
            {
                return _OfficeName;
            }
            set
            {
                OnOfficeNameChanging(value);
                ReportPropertyChanging("OfficeName");
                _OfficeName = StructuralObject.SetValidValue(value, true, "OfficeName");
                ReportPropertyChanged("OfficeName");
                OnOfficeNameChanged();
            }
        }
        private global::System.String _OfficeName;
        partial void OnOfficeNameChanging(global::System.String value);
        partial void OnOfficeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeAbbr
        {
            get
            {
                return _OfficeAbbr;
            }
            set
            {
                OnOfficeAbbrChanging(value);
                ReportPropertyChanging("OfficeAbbr");
                _OfficeAbbr = StructuralObject.SetValidValue(value, true, "OfficeAbbr");
                ReportPropertyChanged("OfficeAbbr");
                OnOfficeAbbrChanged();
            }
        }
        private global::System.String _OfficeAbbr;
        partial void OnOfficeAbbrChanging(global::System.String value);
        partial void OnOfficeAbbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeMedium
        {
            get
            {
                return _OfficeMedium;
            }
            set
            {
                OnOfficeMediumChanging(value);
                ReportPropertyChanging("OfficeMedium");
                _OfficeMedium = StructuralObject.SetValidValue(value, true, "OfficeMedium");
                ReportPropertyChanged("OfficeMedium");
                OnOfficeMediumChanged();
            }
        }
        private global::System.String _OfficeMedium;
        partial void OnOfficeMediumChanging(global::System.String value);
        partial void OnOfficeMediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeCode
        {
            get
            {
                return _OfficeCode;
            }
            set
            {
                OnOfficeCodeChanging(value);
                ReportPropertyChanging("OfficeCode");
                _OfficeCode = StructuralObject.SetValidValue(value, true, "OfficeCode");
                ReportPropertyChanged("OfficeCode");
                OnOfficeCodeChanged();
            }
        }
        private global::System.String _OfficeCode;
        partial void OnOfficeCodeChanging(global::System.String value);
        partial void OnOfficeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeHead
        {
            get
            {
                return _OfficeHead;
            }
            set
            {
                OnOfficeHeadChanging(value);
                ReportPropertyChanging("OfficeHead");
                _OfficeHead = StructuralObject.SetValidValue(value, true, "OfficeHead");
                ReportPropertyChanged("OfficeHead");
                OnOfficeHeadChanged();
            }
        }
        private global::System.String _OfficeHead;
        partial void OnOfficeHeadChanging(global::System.String value);
        partial void OnOfficeHeadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeHeadID
        {
            get
            {
                return _OfficeHeadID;
            }
            set
            {
                OnOfficeHeadIDChanging(value);
                ReportPropertyChanging("OfficeHeadID");
                _OfficeHeadID = StructuralObject.SetValidValue(value, true, "OfficeHeadID");
                ReportPropertyChanged("OfficeHeadID");
                OnOfficeHeadIDChanged();
            }
        }
        private global::System.String _OfficeHeadID;
        partial void OnOfficeHeadIDChanging(global::System.String value);
        partial void OnOfficeHeadIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeDesignation
        {
            get
            {
                return _OfficeDesignation;
            }
            set
            {
                OnOfficeDesignationChanging(value);
                ReportPropertyChanging("OfficeDesignation");
                _OfficeDesignation = StructuralObject.SetValidValue(value, true, "OfficeDesignation");
                ReportPropertyChanged("OfficeDesignation");
                OnOfficeDesignationChanged();
            }
        }
        private global::System.String _OfficeDesignation;
        partial void OnOfficeDesignationChanging(global::System.String value);
        partial void OnOfficeDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fund
        {
            get
            {
                return _Fund;
            }
            set
            {
                OnFundChanging(value);
                ReportPropertyChanging("Fund");
                _Fund = StructuralObject.SetValidValue(value, true, "Fund");
                ReportPropertyChanged("Fund");
                OnFundChanged();
            }
        }
        private global::System.String _Fund;
        partial void OnFundChanging(global::System.String value);
        partial void OnFundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value, "Order");
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeCodeGSIS
        {
            get
            {
                return _OfficeCodeGSIS;
            }
            set
            {
                OnOfficeCodeGSISChanging(value);
                ReportPropertyChanging("OfficeCodeGSIS");
                _OfficeCodeGSIS = StructuralObject.SetValidValue(value, true, "OfficeCodeGSIS");
                ReportPropertyChanged("OfficeCodeGSIS");
                OnOfficeCodeGSISChanged();
            }
        }
        private global::System.String _OfficeCodeGSIS;
        partial void OnOfficeCodeGSISChanging(global::System.String value);
        partial void OnOfficeCodeGSISChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SectorCode
        {
            get
            {
                return _SectorCode;
            }
            set
            {
                OnSectorCodeChanging(value);
                ReportPropertyChanging("SectorCode");
                _SectorCode = StructuralObject.SetValidValue(value, "SectorCode");
                ReportPropertyChanged("SectorCode");
                OnSectorCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _SectorCode;
        partial void OnSectorCodeChanging(Nullable<global::System.Int32> value);
        partial void OnSectorCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> NationalAgency
        {
            get
            {
                return _NationalAgency;
            }
            set
            {
                OnNationalAgencyChanging(value);
                ReportPropertyChanging("NationalAgency");
                _NationalAgency = StructuralObject.SetValidValue(value, "NationalAgency");
                ReportPropertyChanged("NationalAgency");
                OnNationalAgencyChanged();
            }
        }
        private Nullable<global::System.Boolean> _NationalAgency;
        partial void OnNationalAgencyChanging(Nullable<global::System.Boolean> value);
        partial void OnNationalAgencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> project
        {
            get
            {
                return _project;
            }
            set
            {
                OnprojectChanging(value);
                ReportPropertyChanging("project");
                _project = StructuralObject.SetValidValue(value, "project");
                ReportPropertyChanged("project");
                OnprojectChanged();
            }
        }
        private Nullable<global::System.Boolean> _project;
        partial void OnprojectChanging(Nullable<global::System.Boolean> value);
        partial void OnprojectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> locatedinCapitol
        {
            get
            {
                return _locatedinCapitol;
            }
            set
            {
                OnlocatedinCapitolChanging(value);
                ReportPropertyChanging("locatedinCapitol");
                _locatedinCapitol = StructuralObject.SetValidValue(value, "locatedinCapitol");
                ReportPropertyChanged("locatedinCapitol");
                OnlocatedinCapitolChanged();
            }
        }
        private Nullable<global::System.Boolean> _locatedinCapitol;
        partial void OnlocatedinCapitolChanging(Nullable<global::System.Boolean> value);
        partial void OnlocatedinCapitolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HeadCelNo
        {
            get
            {
                return _HeadCelNo;
            }
            set
            {
                OnHeadCelNoChanging(value);
                ReportPropertyChanging("HeadCelNo");
                _HeadCelNo = StructuralObject.SetValidValue(value, true, "HeadCelNo");
                ReportPropertyChanged("HeadCelNo");
                OnHeadCelNoChanged();
            }
        }
        private global::System.String _HeadCelNo;
        partial void OnHeadCelNoChanging(global::System.String value);
        partial void OnHeadCelNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> isActiveOffice
        {
            get
            {
                return _isActiveOffice;
            }
            set
            {
                OnisActiveOfficeChanging(value);
                ReportPropertyChanging("isActiveOffice");
                _isActiveOffice = StructuralObject.SetValidValue(value, "isActiveOffice");
                ReportPropertyChanged("isActiveOffice");
                OnisActiveOfficeChanged();
            }
        }
        private Nullable<global::System.Int32> _isActiveOffice;
        partial void OnisActiveOfficeChanging(Nullable<global::System.Int32> value);
        partial void OnisActiveOfficeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Plantilla_Ordering
        {
            get
            {
                return _Plantilla_Ordering;
            }
            set
            {
                OnPlantilla_OrderingChanging(value);
                ReportPropertyChanging("Plantilla_Ordering");
                _Plantilla_Ordering = StructuralObject.SetValidValue(value, "Plantilla_Ordering");
                ReportPropertyChanged("Plantilla_Ordering");
                OnPlantilla_OrderingChanged();
            }
        }
        private Nullable<global::System.Int32> _Plantilla_Ordering;
        partial void OnPlantilla_OrderingChanging(Nullable<global::System.Int32> value);
        partial void OnPlantilla_OrderingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> isMain
        {
            get
            {
                return _isMain;
            }
            set
            {
                OnisMainChanging(value);
                ReportPropertyChanging("isMain");
                _isMain = StructuralObject.SetValidValue(value, "isMain");
                ReportPropertyChanged("isMain");
                OnisMainChanged();
            }
        }
        private Nullable<global::System.Int32> _isMain;
        partial void OnisMainChanging(Nullable<global::System.Int32> value);
        partial void OnisMainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> IsPhysical
        {
            get
            {
                return _IsPhysical;
            }
            set
            {
                OnIsPhysicalChanging(value);
                ReportPropertyChanging("IsPhysical");
                _IsPhysical = StructuralObject.SetValidValue(value, "IsPhysical");
                ReportPropertyChanged("IsPhysical");
                OnIsPhysicalChanged();
            }
        }
        private Nullable<global::System.Int16> _IsPhysical;
        partial void OnIsPhysicalChanging(Nullable<global::System.Int16> value);
        partial void OnIsPhysicalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email_admin
        {
            get
            {
                return _email_admin;
            }
            set
            {
                Onemail_adminChanging(value);
                ReportPropertyChanging("email_admin");
                _email_admin = StructuralObject.SetValidValue(value, true, "email_admin");
                ReportPropertyChanged("email_admin");
                Onemail_adminChanged();
            }
        }
        private global::System.String _email_admin;
        partial void Onemail_adminChanging(global::System.String value);
        partial void Onemail_adminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email_emp_grouped
        {
            get
            {
                return _email_emp_grouped;
            }
            set
            {
                Onemail_emp_groupedChanging(value);
                ReportPropertyChanging("email_emp_grouped");
                _email_emp_grouped = StructuralObject.SetValidValue(value, true, "email_emp_grouped");
                ReportPropertyChanged("email_emp_grouped");
                Onemail_emp_groupedChanged();
            }
        }
        private global::System.String _email_emp_grouped;
        partial void Onemail_emp_groupedChanging(global::System.String value);
        partial void Onemail_emp_groupedChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pmisModel", Name="vwLoginParameter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwLoginParameter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwLoginParameter object.
        /// </summary>
        /// <param name="euid">Initial value of the euid property.</param>
        public static vwLoginParameter CreatevwLoginParameter(global::System.Int32 euid)
        {
            vwLoginParameter vwLoginParameter = new vwLoginParameter();
            vwLoginParameter.euid = euid;
            return vwLoginParameter;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 euid
        {
            get
            {
                return _euid;
            }
            set
            {
                if (_euid != value)
                {
                    OneuidChanging(value);
                    ReportPropertyChanging("euid");
                    _euid = StructuralObject.SetValidValue(value, "euid");
                    ReportPropertyChanged("euid");
                    OneuidChanged();
                }
            }
        }
        private global::System.Int32 _euid;
        partial void OneuidChanging(global::System.Int32 value);
        partial void OneuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> eid
        {
            get
            {
                return _eid;
            }
            set
            {
                OneidChanging(value);
                ReportPropertyChanging("eid");
                _eid = StructuralObject.SetValidValue(value, "eid");
                ReportPropertyChanged("eid");
                OneidChanged();
            }
        }
        private Nullable<global::System.Int64> _eid;
        partial void OneidChanging(Nullable<global::System.Int64> value);
        partial void OneidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SwipEmployeeID
        {
            get
            {
                return _SwipEmployeeID;
            }
            set
            {
                OnSwipEmployeeIDChanging(value);
                ReportPropertyChanging("SwipEmployeeID");
                _SwipEmployeeID = StructuralObject.SetValidValue(value, true, "SwipEmployeeID");
                ReportPropertyChanged("SwipEmployeeID");
                OnSwipEmployeeIDChanged();
            }
        }
        private global::System.String _SwipEmployeeID;
        partial void OnSwipEmployeeIDChanging(global::System.String value);
        partial void OnSwipEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passcode
        {
            get
            {
                return _passcode;
            }
            set
            {
                OnpasscodeChanging(value);
                ReportPropertyChanging("passcode");
                _passcode = StructuralObject.SetValidValue(value, true, "passcode");
                ReportPropertyChanged("passcode");
                OnpasscodeChanged();
            }
        }
        private global::System.String _passcode;
        partial void OnpasscodeChanging(global::System.String value);
        partial void OnpasscodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value, "RoleId");
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleId;
        partial void OnRoleIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emailaddress
        {
            get
            {
                return _emailaddress;
            }
            set
            {
                OnemailaddressChanging(value);
                ReportPropertyChanging("emailaddress");
                _emailaddress = StructuralObject.SetValidValue(value, true, "emailaddress");
                ReportPropertyChanged("emailaddress");
                OnemailaddressChanged();
            }
        }
        private global::System.String _emailaddress;
        partial void OnemailaddressChanging(global::System.String value);
        partial void OnemailaddressChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pmisModel", Name="vwMergeAllEmployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwMergeAllEmployee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwMergeAllEmployee object.
        /// </summary>
        /// <param name="eid">Initial value of the eid property.</param>
        /// <param name="trNo">Initial value of the trNo property.</param>
        /// <param name="department">Initial value of the Department property.</param>
        /// <param name="appointCoverage">Initial value of the AppointCoverage property.</param>
        /// <param name="telephone">Initial value of the Telephone property.</param>
        /// <param name="bloodtype">Initial value of the bloodtype property.</param>
        /// <param name="canHaveTravel">Initial value of the CanHaveTravel property.</param>
        /// <param name="concurrent">Initial value of the Concurrent property.</param>
        public static vwMergeAllEmployee CreatevwMergeAllEmployee(global::System.Int64 eid, global::System.Int64 trNo, global::System.Int32 department, global::System.DateTime appointCoverage, global::System.String telephone, global::System.String bloodtype, global::System.Int32 canHaveTravel, global::System.Int32 concurrent)
        {
            vwMergeAllEmployee vwMergeAllEmployee = new vwMergeAllEmployee();
            vwMergeAllEmployee.eid = eid;
            vwMergeAllEmployee.trNo = trNo;
            vwMergeAllEmployee.Department = department;
            vwMergeAllEmployee.AppointCoverage = appointCoverage;
            vwMergeAllEmployee.Telephone = telephone;
            vwMergeAllEmployee.bloodtype = bloodtype;
            vwMergeAllEmployee.CanHaveTravel = canHaveTravel;
            vwMergeAllEmployee.Concurrent = concurrent;
            return vwMergeAllEmployee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SwipeId
        {
            get
            {
                return _SwipeId;
            }
            set
            {
                OnSwipeIdChanging(value);
                ReportPropertyChanging("SwipeId");
                _SwipeId = StructuralObject.SetValidValue(value, true, "SwipeId");
                ReportPropertyChanged("SwipeId");
                OnSwipeIdChanged();
            }
        }
        private global::System.String _SwipeId;
        partial void OnSwipeIdChanging(global::System.String value);
        partial void OnSwipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 eid
        {
            get
            {
                return _eid;
            }
            set
            {
                if (_eid != value)
                {
                    OneidChanging(value);
                    ReportPropertyChanging("eid");
                    _eid = StructuralObject.SetValidValue(value, "eid");
                    ReportPropertyChanged("eid");
                    OneidChanged();
                }
            }
        }
        private global::System.Int64 _eid;
        partial void OneidChanging(global::System.Int64 value);
        partial void OneidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 trNo
        {
            get
            {
                return _trNo;
            }
            set
            {
                if (_trNo != value)
                {
                    OntrNoChanging(value);
                    ReportPropertyChanging("trNo");
                    _trNo = StructuralObject.SetValidValue(value, "trNo");
                    ReportPropertyChanged("trNo");
                    OntrNoChanged();
                }
            }
        }
        private global::System.Int64 _trNo;
        partial void OntrNoChanging(global::System.Int64 value);
        partial void OntrNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RowNo
        {
            get
            {
                return _RowNo;
            }
            set
            {
                OnRowNoChanging(value);
                ReportPropertyChanging("RowNo");
                _RowNo = StructuralObject.SetValidValue(value, "RowNo");
                ReportPropertyChanged("RowNo");
                OnRowNoChanged();
            }
        }
        private Nullable<global::System.Int64> _RowNo;
        partial void OnRowNoChanging(Nullable<global::System.Int64> value);
        partial void OnRowNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpName
        {
            get
            {
                return _EmpName;
            }
            set
            {
                OnEmpNameChanging(value);
                ReportPropertyChanging("EmpName");
                _EmpName = StructuralObject.SetValidValue(value, true, "EmpName");
                ReportPropertyChanged("EmpName");
                OnEmpNameChanged();
            }
        }
        private global::System.String _EmpName;
        partial void OnEmpNameChanging(global::System.String value);
        partial void OnEmpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, true, "Position");
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Department
        {
            get
            {
                return _Department;
            }
            set
            {
                if (_Department != value)
                {
                    OnDepartmentChanging(value);
                    ReportPropertyChanging("Department");
                    _Department = StructuralObject.SetValidValue(value, "Department");
                    ReportPropertyChanged("Department");
                    OnDepartmentChanged();
                }
            }
        }
        private global::System.Int32 _Department;
        partial void OnDepartmentChanging(global::System.Int32 value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeAbbr
        {
            get
            {
                return _OfficeAbbr;
            }
            set
            {
                OnOfficeAbbrChanging(value);
                ReportPropertyChanging("OfficeAbbr");
                _OfficeAbbr = StructuralObject.SetValidValue(value, true, "OfficeAbbr");
                ReportPropertyChanged("OfficeAbbr");
                OnOfficeAbbrChanged();
            }
        }
        private global::System.String _OfficeAbbr;
        partial void OnOfficeAbbrChanging(global::System.String value);
        partial void OnOfficeAbbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeName
        {
            get
            {
                return _OfficeName;
            }
            set
            {
                OnOfficeNameChanging(value);
                ReportPropertyChanging("OfficeName");
                _OfficeName = StructuralObject.SetValidValue(value, true, "OfficeName");
                ReportPropertyChanged("OfficeName");
                OnOfficeNameChanged();
            }
        }
        private global::System.String _OfficeName;
        partial void OnOfficeNameChanging(global::System.String value);
        partial void OnOfficeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAdd
        {
            get
            {
                return _EmailAdd;
            }
            set
            {
                OnEmailAddChanging(value);
                ReportPropertyChanging("EmailAdd");
                _EmailAdd = StructuralObject.SetValidValue(value, true, "EmailAdd");
                ReportPropertyChanged("EmailAdd");
                OnEmailAddChanged();
            }
        }
        private global::System.String _EmailAdd;
        partial void OnEmailAddChanging(global::System.String value);
        partial void OnEmailAddChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> employmentstatus_id
        {
            get
            {
                return _employmentstatus_id;
            }
            set
            {
                Onemploymentstatus_idChanging(value);
                ReportPropertyChanging("employmentstatus_id");
                _employmentstatus_id = StructuralObject.SetValidValue(value, "employmentstatus_id");
                ReportPropertyChanged("employmentstatus_id");
                Onemploymentstatus_idChanged();
            }
        }
        private Nullable<global::System.Byte> _employmentstatus_id;
        partial void Onemploymentstatus_idChanging(Nullable<global::System.Byte> value);
        partial void Onemploymentstatus_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AppointCoverage
        {
            get
            {
                return _AppointCoverage;
            }
            set
            {
                if (_AppointCoverage != value)
                {
                    OnAppointCoverageChanging(value);
                    ReportPropertyChanging("AppointCoverage");
                    _AppointCoverage = StructuralObject.SetValidValue(value, "AppointCoverage");
                    ReportPropertyChanged("AppointCoverage");
                    OnAppointCoverageChanged();
                }
            }
        }
        private global::System.DateTime _AppointCoverage;
        partial void OnAppointCoverageChanging(global::System.DateTime value);
        partial void OnAppointCoverageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cause
        {
            get
            {
                return _Cause;
            }
            set
            {
                OnCauseChanging(value);
                ReportPropertyChanging("Cause");
                _Cause = StructuralObject.SetValidValue(value, true, "Cause");
                ReportPropertyChanged("Cause");
                OnCauseChanged();
            }
        }
        private global::System.String _Cause;
        partial void OnCauseChanging(global::System.String value);
        partial void OnCauseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                if (_Telephone != value)
                {
                    OnTelephoneChanging(value);
                    ReportPropertyChanging("Telephone");
                    _Telephone = StructuralObject.SetValidValue(value, false, "Telephone");
                    ReportPropertyChanged("Telephone");
                    OnTelephoneChanged();
                }
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bloodtype
        {
            get
            {
                return _bloodtype;
            }
            set
            {
                if (_bloodtype != value)
                {
                    OnbloodtypeChanging(value);
                    ReportPropertyChanging("bloodtype");
                    _bloodtype = StructuralObject.SetValidValue(value, false, "bloodtype");
                    ReportPropertyChanged("bloodtype");
                    OnbloodtypeChanged();
                }
            }
        }
        private global::System.String _bloodtype;
        partial void OnbloodtypeChanging(global::System.String value);
        partial void OnbloodtypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> TimeCode
        {
            get
            {
                return _TimeCode;
            }
            set
            {
                OnTimeCodeChanging(value);
                ReportPropertyChanging("TimeCode");
                _TimeCode = StructuralObject.SetValidValue(value, "TimeCode");
                ReportPropertyChanged("TimeCode");
                OnTimeCodeChanged();
            }
        }
        private Nullable<global::System.Byte> _TimeCode;
        partial void OnTimeCodeChanging(Nullable<global::System.Byte> value);
        partial void OnTimeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CanHaveTravel
        {
            get
            {
                return _CanHaveTravel;
            }
            set
            {
                if (_CanHaveTravel != value)
                {
                    OnCanHaveTravelChanging(value);
                    ReportPropertyChanging("CanHaveTravel");
                    _CanHaveTravel = StructuralObject.SetValidValue(value, "CanHaveTravel");
                    ReportPropertyChanged("CanHaveTravel");
                    OnCanHaveTravelChanged();
                }
            }
        }
        private global::System.Int32 _CanHaveTravel;
        partial void OnCanHaveTravelChanging(global::System.Int32 value);
        partial void OnCanHaveTravelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Concurrent
        {
            get
            {
                return _Concurrent;
            }
            set
            {
                if (_Concurrent != value)
                {
                    OnConcurrentChanging(value);
                    ReportPropertyChanging("Concurrent");
                    _Concurrent = StructuralObject.SetValidValue(value, "Concurrent");
                    ReportPropertyChanged("Concurrent");
                    OnConcurrentChanged();
                }
            }
        }
        private global::System.Int32 _Concurrent;
        partial void OnConcurrentChanging(global::System.Int32 value);
        partial void OnConcurrentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthD
        {
            get
            {
                return _BirthD;
            }
            set
            {
                OnBirthDChanging(value);
                ReportPropertyChanging("BirthD");
                _BirthD = StructuralObject.SetValidValue(value, true, "BirthD");
                ReportPropertyChanged("BirthD");
                OnBirthDChanged();
            }
        }
        private global::System.String _BirthD;
        partial void OnBirthDChanging(global::System.String value);
        partial void OnBirthDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Salary
        {
            get
            {
                return _Salary;
            }
            set
            {
                OnSalaryChanging(value);
                ReportPropertyChanging("Salary");
                _Salary = StructuralObject.SetValidValue(value, "Salary");
                ReportPropertyChanged("Salary");
                OnSalaryChanged();
            }
        }
        private Nullable<global::System.Decimal> _Salary;
        partial void OnSalaryChanging(Nullable<global::System.Decimal> value);
        partial void OnSalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpNameFull
        {
            get
            {
                return _EmpNameFull;
            }
            set
            {
                OnEmpNameFullChanging(value);
                ReportPropertyChanging("EmpNameFull");
                _EmpNameFull = StructuralObject.SetValidValue(value, true, "EmpNameFull");
                ReportPropertyChanged("EmpNameFull");
                OnEmpNameFullChanged();
            }
        }
        private global::System.String _EmpNameFull;
        partial void OnEmpNameFullChanging(global::System.String value);
        partial void OnEmpNameFullChanged();

        #endregion

    }

    #endregion

}
