//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.SMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMS.SMSWebServiceSoap")]
    public interface SMSWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEND_SMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SEND_SMS(string sendTo, string msg, int isid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEND_SMS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SEND_SMSAsync(string sendTo, string msg, int isid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSWebServiceSoapChannel : IMS.SMS.SMSWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSWebServiceSoapClient : System.ServiceModel.ClientBase<IMS.SMS.SMSWebServiceSoap>, IMS.SMS.SMSWebServiceSoap {
        
        public SMSWebServiceSoapClient() {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SEND_SMS(string sendTo, string msg, int isid) {
            return base.Channel.SEND_SMS(sendTo, msg, isid);
        }
        
        public System.Threading.Tasks.Task<string> SEND_SMSAsync(string sendTo, string msg, int isid) {
            return base.Channel.SEND_SMSAsync(sendTo, msg, isid);
        }
    }
}
